name: Run linters and formatters

on:
  pull_request:

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      # checkout soruce code
      - name: Checkout code
        uses: actions/checkout@v3

      # setup Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # install hatch
      - name: Install hatch
        run: |
          python -m pip install --upgrade pip
          pip install hatch

      # scan for markdown linting errors
      - name: Run pymarkdownlnt on markdown files
        shell: bash
        run: |
          make lint
