on:
  push:
  pull_request:

jobs:
  run-test-cases:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3
      - name: Test
        run: make build-test
      - name: Test model server
        run: make test-model-server
      - name: Test estimator
        run: make test-estimator
        timeout-minutes: 5
      - name: Test pipeline
        run: make test-pipeline
      - name: Test offline trainer
        run: make test-offline-trainer